"""
context_data.py

Contains all embedded context for the Cover Letter Generator App. 
These are multi-line strings to avoid file reads in Streamlit Cloud.
"""

# -------------------------------------------------------------------
# CV Text
# -------------------------------------------------------------------
CV_TEXT = """
NICOLAS DE CASTRO                                                                                                                             
NDecastro26@gsb.columbia.edu, (332) 273-5280 
EDUCATION 
 
COLUMBIA BUSINESS SCHOOL 
MBA (STEM-designated), Product Management & Data Analytics and AI Pathway, May 2026 
Leadership: Tech Club, AI Club, LATAM Business Association 
 
New York, NY 
2024 – 2026 
UNIVERSIDAD DE LOS ANDES 
BS, Industrial Engineering 
Minor: Business Law 
 
Bogota, Colombia 
2015 – 2019 
EXPERIENCE 
CAPITAL ONE 
 
New York, NY 
2025 
Gen AI Product Manager MBA Intern (2025) 
 Led hypothesis-driven user and technical discovery to diagnose AI search issues; evaluated three GenAI architectures (Graph 
RAG, Agentic RAG, Query Expansion) with data science and engineering on impact, effort, and risk to select the optimal solution  
 Independently coded a Python query-expansion prototype to validate selected approach; benchmarked against baseline retrieval, 
confirming a 14% improvement in search precision across enterprise use cases 
 Translated prototype results into a PRD and business case; created an executive deck and presented to senior VPs quantifying 
~$400K in annual savings and +3s faster agent search times, securing roadmap inclusion 
 
VISA INC Bogota, Colombia  
2023 – 2024 
Product Manager (2023-2024) 
 Ideated GTM plan for agro card in Andean region through comprehensive benchmarking and competitive analysis; presented 
findings to leadership, securing buy-in and incentives, boosting adoption of 3M cards and US$11M in transactional revenue 
 
TREINTA (Y COMBINATOR – W21) 
Startup empowering LATAM SMBs (record-breaking $60 Million Colombia Series A) 
Bogota, Colombia 
2021 – 2023 
Senior Product Manager (2022-2023), Product Manager (2021-2022) 
 Designed, prioritized, and executed roadmaps for Treinta’s flagship accounting app for SMBs; shipped features that solved user 
and business needs, raising retention by +20% and activation by +15%, contributing to a record US$60M Series A in Colombia 
 Directed tribe as Group Product Manager, strengthening Agile processes and PRD documentation across 3 squads with 3 PMs, 2 
designers, and 10 developers, improving collaboration and doubling release cadence 
 Ideated tribe OKRs and KPIs through structured problem solving, aligning business and user goals and empowering squads to 
deliver +8 customer-facing features for +1M users across 18 countries 
 Devised and executed an API-integration project with a third-party provider, bringing a money-losing product to breakeven and 
enabling 12K SMBs to increase monthly revenue by 17% 
 Conducted user discovery and A/B testing to enhance Treinta’s flagship application UX/UI; guided engineering and design teams 
in Agile to implement improvements, lifting daily active usage (DAU) by 9% across a +1M user base 
 
MASTERCARD Bogota, Colombia 
2019 – 2021 
Consultant (2021), Associate Consultant (2019-2021) 
• Led, designed, and executed renewal strategy for debit card portfolio in biggest bank in Colombia; generated additional profit of +US$ 20MM.
  - Directed cross-functional teams and PMO sessions to migrate +3M cards within a 10M-card portfolio.
  - Conducted +10MM client segmentation to maximize migration profitability by 19%.
  - Coded and implemented communication triggers and a transactional analytics model, improving migrated-client spend by ~7%.
  - Created solid standardized process for reusing migration best practices within the Mastercard regional team.
• Spearheaded life cycle optimization project for one of the largest issuers in the Caribbean: increased customer transactionality by 12% and overall spending by ~5%.
  - Created the bank's first cardholder segmentation model using advanced data analysis techniques (K-means in RStudio).
  - Complemented data with insights from user focus groups and experimented with test & learn tools to optimize communication channels, tones, and promotions.
• Conducted root-cause analysis of fraud and authorization issues for Colombia's largest bank; coordinated cross-functional Product, Risk, and Marketing teams to deploy optimized controls, improving approval rates by 17 p.p.
• Identified and presented initiatives to improve authorization & fraud key results for the largest issuer in the Caribbean, increasing revenues by ~US$ 5MM.
• Designed value proposition strategy for an innovative credit card fostering financial inclusion within the agricultural sector, resulting in the adoption of +25K cards.
• Structured and executed replicable training initiatives to coach new hires in consulting frameworks and analytics techniques.
 
CMILLAS (Social entrepreneurship supporting education of marginalized children) Bogotá, Colombia
Co-founder & Volunteer (2019 - 2021)
• Led creation of alliance with two major foundations in Colombia (Laudes infantis & Alianza Educativa).
• Developed and co-managed volunteer program, successfully building network of over 30 volunteers who supported educational needs of ~90 children.

ADDITIONAL INFORMATION 
 
Certifications: Supervised ML: Regression and Classification & Adv. Algorithms | Python for Data Science, AI & Development 
Technical Skills: Python | SQL | Claude | Cursor | n8n | LangChain | FAISS | Amplitude & Google Analytics | Jira | Figma | Split.io 
Additional Languages: Spanish (Native) | German (Advanced) | Portuguese (Basic) 
Interests: Running (13.1 miles, 91st percentile pace) | AI builder & Vibe Coding: consistently leveraging AI tools in my free time to build personal projects with RAG, MCP agents, LLMs, and vector DBs to solve real problems.

"""

# -------------------------------------------------------------------
# Full Story Bank
# -------------------------------------------------------------------
STORY_BANK = """
Name Short Version Long Version
Story 1: Going Above and Beyond for a Customer – Mastercard triggersSituation:o        While working at Mastercard as a Consultant, I led a complex project to help the largest bank in Colombia migrate its customer portfolio.o        A major roadblock arose: the bank needed behavioral intelligence to send activation and engagement messages but lacked the tools and manpower. This issue was outside our advisory scope and jeopardized the project.Task:o        My task was to go beyond my project responsibilities and find a solution to automate transactional intelligence for the client to ensure project continuity.Action:o        Leveraged my learning in RStudio to develop a transactional intelligence model during my personal time.o        Designed the model to analyze high-level transactional data to determine which customers to target, what message to send, and which communication channel to use based on LTV .o        Engaged proactively with the client to demonstrate the economic benefits, conducted demos, and led testing cycles to ensure model reliability.Result:o        The bank adopted the model, removing the roadblock and successfully continuing the migration process.o        The model’s triggers increased per-user spending by 7%.
Full Version (STAR)•        Situation:o        During my time at Mastercard as a Consultant, I was part of a high-stakes project assisting the largest bank in Colombia with migrating its customer portfolio. This was one of the largest banks in Latin America.o        Midway through the project, we faced a significant roadblock. The bank needed to send activation and engagement messages to their migrated customer portfolio. However, they lacked the behavioral intelligence and manpower to analyze who was transacting, when, and where. This capability was critical for the project’s success but was not part of Mastercard’s advisory services.•        Task:o        My responsibility was to think creatively and go beyond the usual project scope to solve this problem. I needed to develop a tool or process that could provide the bank with the required insights to continue the migration project.•        Action:o        In my spare time outside of the project’s regular scope, I learned and used RStudio to create a transactional intelligence model.o        The model automated the analysis of transactional data to identify customers to target, personalized messaging based on their LTV , and optimal communication channels.o        I presented the model’s potential benefits to the client, including economic impact, and led a demo and test cycles to ensure its reliability.•        Result:o        The client approved the use of the model, eliminating the blocker, and the migration project progressed as planned.o        The communication triggers implemented via the model increased per-user spending by 7%, demonstrating significant ROI.
Story 2: Problem solving and cross functional – Treinta Activation Challenges in POS Software Launch Situation:o        At Treinta, I was launching a Point of Sale (POS) software for restaurants. Despite its potential, we struggled to increase weekly and monthly active users post-launch.Task:o        My task was to identify the root cause of non increasing MAUs and implement solutions to improve it.Action:o        Analyzed data and understand that root cause was activation indicators.o        Conducted interviews with customers and identified activation funnel challenges; customers struggled to reach the product’s “aha” moment.o        Proposed and prioritized short, medium, and long-term solutions:         Worked with design and engineering to develop an onboarding feature into the product roadmap.        Convinced the marketing team to prioritize explanatory videos and input the user needs into the script.        Personally conducted 50+ video training sessions with an analyst to onboard key users, stretching working hours for several weeks.Result:o        Activated nearly all users trained via video sessions.o        Deployed YouTube training videos and email campaigns, along with the onboarding feature.o        Increased activation rates by 17 percentage points, significantly boosting MAU.
Full Version (STAR)•        Situation:o        While working at Treinta, I was responsible for launching a Point of Sale (POS) software targeted at restaurants. The product offered features like order registration and inventory tracking, along with value-added services.o        After the initial launch, we encountered challenges in scaling weekly and monthly active users, falling short of our targets.•        Task:o        I was tasked with diagnosing the root cause of our low MAUs and designing and executing an actionable plan to improve user engagement and retention.•        Action:o        Analyzed product usage data and discovered that customers were struggling to activate and fully adopt the software, failing to reach its “aha” moment.o        Conducted interviews with non-activated users to understand their first-time use challenges.o        Proposed a set of prioritized solutions:         Short term: Collaborated with the marketing team to create and distribute explanatory videos.        Medium term: Personally led 50+ video training sessions alongside an analyst to onboard key users, stretching our working hours over several weeks.        Long term: Integrated an onboarding flow into the roadmap to streamline future activations.•        Result:o        The combined efforts led to a 17-percentage-point increase in activation rates, significantly boosting MAUs.o        Nearly all users trained via video sessions became active, while the onboarding feature and training content continued to deliver value post-launch.
Story 3: Detail Orientation and Insisting comm - Mastercard Country Manager DR Situation:o        While working at Mastercard, I was leading a project with the largest bank in the Dominican Republic.o        The Mastercard Country Manager requested additional market insights to understand bank performance indicators, on top of my existing project responsibilities.Task:o        Tasked with updating the existing market insights model and extracting actionable data insights for the Country Manager.Action:o        While updating the model, I meticulously validated the data and calculations.o        Identified that the existing model was only considering major banks and overlooked smaller players, leading to inaccurate market share reporting.o        Discovered that Mastercard’s debit share was declining when including smaller banks, an issue previously unnoticed.o        Updated the model to incorporate smaller players, created a detailed presentation highlighting the issue, and presented it to the Country Manager.Result:o        The Country Manager was surprised and thanked me for uncovering this oversight.o        Collaborated with business development teams, discovering competitor activity affecting the market share.o        This insight led to a new commercial strategy to counteract the decline, helping stabilize Mastercard’s market share.
Full Version (STAR)•Situation:oAt Mastercard, I was managing a project with the largest bank in the Dominican Republic.oThe Country Manager approached my team to request additional market insights on Mastercard’s portfolio performance to support broader business objectives. This was in addition to my primary project responsibilities.•Task:oI was tasked with updating the existing data model and delivering insights to the Country Manager, ensuring accuracy and reliability of the analysis.•Action:oWhile updating the model, I conducted a meticulous review of the data and calculations to ensure quality and accuracy.oIdentified a critical flaw: the model was calculating market share based only on major banks and omitted smaller players, skewing the results.oDiscovered that Mastercard’s debit share, when factoring in smaller players, was declining — a trend unnoticed by the previous team and the Country Manager.oUpdated the model to include data from smaller players, created a detailed analysis presentation, and communicated this issue and its implications to the Country Manager.•Result:oThe Country Manager was surprised by the findings and thanked me for bringing this to light.oCollaborated with business development teams to investigate further, uncovering that a competitor was striking deals to migrate portfolios.oThis insight enabled the team to craft a targeted commercial strategy, mitigating the market share decline and reinforcing Mastercard’s position in the region
Story 4: Treinta - Creating Success Through Team Processes and MotivationSituation:o        At Treinta, I joined as a Product Manager for the flagship mobile app, leading a disorganized engineering and design team with low morale and infrequent releases.Task:o        Tasked with steering the team towards better processes, boosting motivation, and increasing release frequency. With no Scrum Master in place, I had to lead this effort independently.Action:o        Established an Agile operation model with daily stand-ups, refinement ceremonies, and retrospectives to improve collaboration.o        Created detailed user stories, addressing every edge case, and ensured development requirements were clear and actionable.o        Fostered team morale by organizing social events and formal 1:1 sessions to rebuild trust among engineering, design, and product teams.Result:o        Team morale improved significantly, as noted in retrospective feedback.o        Processes were adopted as best practices across other squads in the company.o        Release frequency improved from biweekly to weekly, with significantly fewer bugs.
Full Version (STAR)•        Situation:o        At Treinta, I took on the role of Product Manager for the company’s flagship mobile app. The engineering and design teams I worked with were unorganized, demotivated, and struggling to meet goals. Release cycles were infrequent, and team morale was low.•        Task:o        My task was to implement effective processes and motivate the team to improve collaboration, increase release frequency, and ensure better outcomes.•        Action:o        Studied Agile methodologies and implemented an operation model tailored to our needs, introducing daily stand-ups, refinement ceremonies, and retrospectives.o        Identified and resolved the issue of unclear development requirements by creating highly detailed user stories that included all possible edge cases.o        Organized social events and formal 1:1 settings to rebuild trust among engineering, product, and design teams.•        Result:o        Morale improved significantly, with positive feedback from retrospectives.o        My processes were highlighted as best practices and adopted by other squads in the company.o        Release cycles increased from Monthly to weekly, with a noticeable reduction in BUGs per release (20 to less than 6)..
Story 5: Mentoring Underperforming Intern to Success -TreintaSituation:o        At Treinta, I worked with an intern assigned to me who was underperforming. My superiors were hesitant to extend his contract as an analyst.Task:o        Tasked with improving the intern’s performance and helping him succeed professionally.Action:o        Used a clarification matrix to evaluate his performance across key dimensions.o        Identified gaps in communication and problem-solving, providing detailed feedback and improvement examples.o        Designed specific next steps and projects to address his development areas, supervising his progress closely.o        Set clear goals and timelines to track and validate improvements.Result:o        The intern’s motivation improved dramatically, and his performance exceeded expectations.o        Superiors extended his contract, and he later replaced me as Product Manager at Treinta, demonstrating trust in his capabilities and my mentorship process.
Full Version (STAR)•Situation:oDuring my tenure at Treinta, I was assigned an intern who was struggling with performance issues. His underperformance led my superiors to question whether he should be offered a full-time analyst position.•Task:oMy task was to help the intern enhance his performance and skillset, ultimately enabling him to succeed professionally.•Action:oConducted a thorough evaluation of his work using a clarification matrix to pinpoint strengths and areas needing improvement.oIdentified communication and problem-solving as critical gaps and provided concrete examples of improvement opportunities.oDesigned tailored projects and tasks to address his weaknesses, offering hands-on supervision and guidance.oEstablished specific goals and timelines to track progress and validate outcomes.•Result:oThe intern’s motivation and performance improved significantly under my mentorship.oMy superiors were impressed by his transformation and extended him a full-time analyst offer.oHe later replaced me as Product Manager at Treinta, a testament to his growth and the success of my mentorship.
Story 6: Treinta - Using Data to Support Hypotheses and Redirect FocusShort Bullet-Point Version (STAR)Situation:o        At Treinta, I was the Product Manager for the bookkeeping app, tasked with cross-selling a large MAU base to a B2B marketplace for mom-and-pop stores.o        Despite my concerns about engineering priorities, I committed to management’s decision to test the monetization hypothesis with new features.Task:o        After the cross-sell features failed to meet objectives, I needed to identify and explain why users were not converting.Action:o        Set up detailed measurement events in Amplitude to gather qualitative and quantitative feedback.o        Analyzed the conversion funnel and interviewed users, identifying a pattern: many users in rural areas clicked on cross-sell banners but could not convert due to lack of B2B service coverage in those regions.o        Highlighted this overlooked issue to management, showing that user location data did not align with assumptions about urban concentration.Result:o        Management recognized the limitations of the hypothesis and the thorough execution despite challenges.o        The team redirected focus to prioritize features targeting urban users, leading to more impactful initiatives that eventualy increased DAU/MAU 9pp.
Full Version (STAR)•        Situation:o        At Treinta, I managed the bookkeeping app, a product with a large base of MAUs enjoying a free service. Management tasked me with cross-selling this user base to a B2B marketplace for mom-and-pop stores.o        Although I believed engineering priorities lay elsewhere, I committed to management’s directive and worked to test their monetization hypothesis through new features.•        Task:o        After implementing cross-sell features, I was responsible for identifying why they did not achieve the desired results and presenting my findings to management.•        Action:o        Proactively set up detailed measurement events in Amplitude to capture user behavior and feedback during the design phase.o        Analyzed conversion funnel data, identifying that while many users engaged with cross-sell banners, most resided in rural areas without access to the B2B service.o        Conducted user interviews to confirm findings, revealing that management had overlooked the lack of rural coverage when prioritizing the initiative.•        Result:o        Presented clear evidence to management, demonstrating the complexity of the challenge and validating the team’s efforts.o        This allowed the team to shift focus back to higher-priority features, such as those targeting urban users, leading to more effective outcomes that eventualy increased DAU/MAU 9pp.
Story 7: Mentoring RStudio Bootcamp LatAm Offices - MastercardSituation:o        At Mastercard, I had been using RStudio as an analytics tool to add value to client projects by delivering fast and impactful insights, even for tasks outside the project’s scope.Task:o        Recognized the interest from other analysts in learning RStudio and decided to organize a Bootcamp to train them in practical use cases, helping enhance client project value.Action:o        Engaged with teams across Mastercard LatAm to understand common data challenges and analytics needs.o        Collaborated with project managers to identify impactful use cases for quick wins.o        Designed reusable code snippets, practical exercises, and instructional materials tailored to these use cases.o        Secured time from leadership to host weekly 2-3 hour Bootcamp sessions with over 20 participants.Result:o        More than 20 analysts and consultants gained practical RStudio skills, enhancing project delivery.o        Several participants became specialists in specific use cases, developing advanced analytics capabilities.o        LatAm offices gained a reputation as a hub for analytics expertise, attracting new commercial opportunities.
Full Version (STAR)•Situation:oDuring my tenure at Mastercard, I extensively used RStudio to deliver fast, actionable insights for clients, even for tasks outside the project’s scope. This added significant value to client projects.•Task:oNoticed growing interest from analysts to learn RStudio, so I took the initiative to design a Bootcamp to equip them with practical skills for common analytics challenges.•Action:oConsulted with teams across Mastercard LatAm to identify shared pain points in data management and analytics.oWorked with project managers to prioritize use cases that would provide quick wins for client projects.oCreated detailed training materials, including reusable code, practical exercises, and explanations of the tool’s functionality.oHosted weekly 2-3 hour sessions with over 20 participants, teaching foundational and advanced use cases.•Result:oOver 20 analysts and consultants gained practical skills in RStudio, significantly improving their ability to deliver value to clients.oSome participants became experts in specific use cases, further advancing the team’s analytics capabilities.oThe LatAm offices became recognized as a hub for analytics excellence, attracting more business opportunities.
Story 8: Cmillas - Supporting Education in Marginalized CommunitiesSituation:o        While in university and at Mastercard, I wanted to create a social project focused on improving education for underprivileged communities in Colombia.Task:o        Aimed to enhance educational outcomes by addressing key challenges faced by children in marginalized communities, such as lack of parental support for homework.Action:o        Partnered with individuals from diverse backgrounds to gain insights into educational challenges.o        Engaged with parents in marginalized communities to understand their pain points and identified the lack of time and knowledge to assist their children with schoolwork.o        Recruited over 30 university students and professionals as volunteer mentors.o        Formed an alliance with a foundation to provide structured mentorship programs and coordinated virtual sessions.o        Acted as the organization’s leader, managing operations and volunteering personally.Result:o        Supported the educational development of over 90 children across two years.o        Positive qualitative feedback from nearly 30 families highlighted the program’s impact in helping children advance to the next school year.
Full Version (STAR)•Situation:oWhile pursuing my university studies and working at Mastercard, I wanted to contribute to education in marginalized communities in Colombia, inspired by the transformative power of education in my own life.•Task:oSet out to improve the educational experience for children in these communities by addressing the lack of parental support for homework and school activities.•Action:oCollaborated with individuals from diverse professional backgrounds to design an impactful approach to supporting education.oConducted interviews with parents in marginalized communities to identify key challenges, discovering that many lacked the time or knowledge to help their children with homework.oMobilized over 30 university students and professionals as volunteer mentors to address these gaps.oPartnered with a local foundation to establish a structured mentorship program and coordinated virtual sessions between volunteers and children.oTook on leadership responsibilities, managing operations and participating as a volunteer mentor.•Result:oOver two years, Cmillas supported the educational development of more than 90 children in marginalized communities.oQualitative feedback from nearly 30 families demonstrated the program’s positive impact, helping children advance academically and gain confidence in their studies
Story 9: Visa - Delivering an Agro Payment SolutionSituation:o        At Visa, payment solutions for agro users in the region were neglected but had high potential.o        No ongoing projects existed in this space, but I hypothesized significant business opportunity.Task:o        Collaborate with the sales team to create a product and commercial proposal for agro payment solutions despite the risks of entering an untested market.Action:o        Conducted market sizing for Visa and partner banks.o        Identified farmers' pain points through focus groups and discussions with industry leaders.o        Benchmarked competing solutions to craft a unique value proposition.o        Mapped the most promising bank partner and presented a go-to-market (GTM) plan to leadership and sales teams.Result:o        Leadership approved the GTM plan, and it was executed with a Spanish bank.o        Generated an estimated $11M USD in yearly revenue potential, establishing Visa as a leader in the agro payment segment.
Full Version (STAR)•Situation:oWhile working at Visa, I identified a gap in the market: payment solutions tailored for agro users in the region were overlooked by the regional team. Despite no ongoing projects, I believed addressing this opportunity could significantly enhance Visa’s sales metrics.•Task:oI was tasked with collaborating with the sales team to conceptualize and pitch a new product and commercial proposal for agro payment solutions. This was risky because Visa had not ventured into this area in the region before.•Action:oTo understand the opportunity, I conducted extensive market research to size the potential impact for Visa and its partner banks.oOrganized focus groups with farmer association leaders and spoke with key industry players to identify pain points, particularly around payment accessibility and financing.oBenchmarked existing solutions in the market to differentiate Visa’s offering and define its unique value proposition.oIdentified the bank with the highest potential for collaboration and developed a comprehensive go-to-market plan, which I presented to the leadership and sales teams.•Result:oThe leadership team approved the GTM plan, which was implemented with a Spanish bank.oThe project created a projected $11M USD in annual revenue potential, solidifying Visa’s position in an untapped market and fostering innovation in the agro payment sector.
Story 10: Treinta Call center - Quick Decision-Making Under Tight DeadlinesShort Bullet-Point Version (STAR)Situation:o        At Treinta, we faced low retention metrics due to users not understanding the app's benefits within the first month.o        With tight deadlines to meet KPIs, I hypothesized that calling and guiding users could improve retention.Task:o        Prove the hypothesis with limited resources: myself, one customer support agent, and an intern.Action:o        Jumped into action, taking ownership of the experiment beyond my usual product role.o        Designed and implemented processes to execute and measure the impact of reactivation calls.o        Developed detailed call scripts and FAQs to guide the team and address common user questions.o        Personally monitored and analyzed call conversations to validate user pain points and improve strategies.•        Result:o        Confirmed hypothesis: direct user contacts improved onboarding and retention.o        Based on the results, a dedicated division was created to scale the approach, further enhancing user retention.o        Achieved reactivation objectives, significantly improving retention metrics by 9%
Full Version (STAR)•        Situation:o        At Treinta, retention metrics showed a significant drop-off within the first month as users struggled to understand the app’s functionality and benefits. We had a short deadline to meet KPI targets, and I hypothesized that direct user engagement through calls could address this issue.•        Task:o        With limited resources—just myself, a customer support agent, and an intern—I needed to design and execute a strategy to validate this hypothesis quickly and effectively.•        Action:o        Took ownership of the experiment, going beyond my product management responsibilities to develop and lead the initiative.o        Established clear objectives and designed processes to execute and measure the reactivation effort.o        Created comprehensive call scripts and FAQs to guide the team, ensuring consistency in user communication.o        Personally monitored and analyzed user calls to validate pain points and refine the approach based on real-time feedback.•        Result:o        The hypothesis proved correct: users responded positively to direct engagement and onboarding support.o        The success of the pilot led to the creation of a dedicated division to scale the initiative, further boosting user retention metrics.o        Achieved reactivation objectives, significantly improving retention metrics by 11%
Story 11: Treinta - Improving Retention Through Product DevelopmentShort Bullet-Point Version (STAR)Situation:o        At Treinta, I managed the flagship bookkeeping app used by over 1M mom-and-pop stores across 18 LATAM countries to manage finances and inventory.Task:o        Tasked with improving retention through product development to increase MAUs, a critical metric for securing Series A funding.Action:o        Created retention dashboards to establish a baseline and analyze churned users.o        Conducted a user-centric approach (focus groups, interviews, surveys) to understand user preferences and pain points.o        Performed a regression analysis to identify features correlated with long-term retention.o        Mapped three key improvement areas: performance/reliability, user experience friction, and usability/onboarding.o        Collaborated with engineering and design teams to develop a robust feature roadmap addressing these areas.Result:o        Launched 4+ features that increased overall retention by 11 percentage points and boosted engagement (DAU/MAU) by 9 percentage points.
Full Version (STAR)•Situation:oAs Product Manager at Treinta, I led the flagship bookkeeping app, which was critical to business metrics and used by over 1M mom-and-pop stores in 18 LATAM countries for managing finances and inventory.•Task:oMy goal was to improve user retention via product development to increase MAUs, a key driver for achieving the next Series A funding milestone.•Action:oDeveloped retention dashboards to calculate baseline retention and analyze churned users.oConducted a user-centric analysis through focus groups, interviews, and surveys with churned and high-value users to understand app strengths and improvement opportunities.oPerformed a regression analysis to identify feature engagement correlated with long-term retention.oIdentified three key improvement areas: performance/reliability, user experience friction in inventory management, and usability/onboarding.oCollaborated with engineering and design teams to create a feature roadmap addressing these improvement areas.•Result:oSuccessfully launched 4+ high-impact features.oAchieved an 11 percentage-point increase in retention and a 9 percentage-point improvement in DAU/MAU engagement metrics.
Story 12: Treinta - PM Inventory Design improvement to Boost Retention Short Bullet-Point Version (STAR)Situation:o        At Treinta, the inventory feature allowed users to track stock levels and reduce pilferage but had low adoption and engagement.Task:o        Tasked with identifying and resolving barriers to inventory adoption to improve user retention.Action:o        Created dashboards and two metrics to measure inventory usage: users with at least one item in inventory and transactions with inventory items.o        Implemented Amplitude events and screen recording software to map friction points in user workflows.o        Conducted user interviews and gathered feedback on pain points.o        Benchmarked similar apps to identify potential solutions.o        Collaborated with design and engineering to deliver three high-impact features addressing user pain points.Result:o        Improved inventory engagement metrics:        Users with inventory increased from 28% to 47%.        Transactions with inventory items increased from 13% to 31%.o        Combined with other features, contributed to an 7 percentage-point improvement in retention and a 15 percentage-point increase in activation.
Full Version (STAR)•Situation:oAt Treinta, the inventory feature was crucial for users to track stock levels, avoid pilferage, and manage restocking. However, adoption and engagement rates were low, limiting retention.•Task:oMy task was to analyze barriers to inventory adoption and implement solutions to improve usage and retention.•Action:oDeveloped two metrics to track inventory engagement: users with at least one inventory item and transactions with inventory items.oBuilt dashboards and implemented Amplitude events alongside screen recording software to identify friction points in the user journey.oConducted user interviews to gather qualitative insights on pain points and areas for improvement.oBenchmarked similar apps to identify innovative solutions and best practices.oCollaborated with design and engineering teams to deliver three high-impact features to address user pain points and improve inventory usability.•Result:oAchieved significant improvements in inventory engagement metrics:Users with inventory increased from 28% to 47%.Transactions with inventory items increased from 13% to 25%.oThese improvements, along with other initiatives, drove an 11 percentage-point increase in retention and a 15 percentage-point improvement in activation rates.
Story 13: FAILURE - BOOK LITE Short Bullet-Point Version (STAR)Situation:o        Managed Treinta’s bookkeeping app, designed to help LATAM micro-businesses digitalize basic accounting and inventory management. Many relied on manual, time-consuming processes like notebooks.Task:o        Tasked with creating features to automate transaction recording, attract users, and drive cross-sell opportunities into Treinta’s monetized B2B marketplace.Action:o        Conducted interviews and focus groups to understand reliance on manual processes.o        Launched an MVP with features to automate transaction recording, validated through A/B testing.o        Discovered low adoption due to a critical oversight: users avoided using phones in daily operations in high-risk areas.o        Pivoted strategy, focusing on alternative monetization approaches.Result:o        Avoided unnecessary development costs for an impractical solution.o        Delivered alternative strategies that brought in 3,000+ paying users.o        Learned to dive deeper into customer context during research and validate assumptions before scaling.o        Ensured future solutions aligned with user needs, their environment, and behaviors.
Full Version (STAR)•Situation:oAt Treinta, I managed the bookkeeping app, which aimed to help micro-businesses in LATAM replace manual processes with digital tools. Many businesses relied on paper notebooks to track transactions, a time-consuming process that often took hours each week to calculate and manage. I identified an opportunity to digitalize this process, saving users time and helping them better understand their operations.•Task:oMy goal was to develop features that automated transaction recording for these businesses, attract more users to the app, and support Treinta’s broader strategy of cross-selling users into its monetized B2B marketplace.•Action:oConducted interviews and focus groups to understand why users preferred manual processes. I hypothesized that a simple digital tool replicating and improving these manual methods could address their pain points.oPrioritized and launched an MVP with automation features, validating its impact through A/B testing.oThe MVP showed low adoption, prompting deeper analysis and customer feedback. This revealed a critical oversight: many users, especially in high-risk areas, were reluctant to use their phones during daily operations due to safety concerns. This made the proposed solution impractical.oPivoted the strategy, focusing on alternative monetization opportunities better aligned with user behavior and needs.•Result:oAvoided unnecessary development costs for features that would not meet customer needs.oShifted focus to alternative strategies that successfully brought in over 3,000 paying users.oGained valuable insights on the importance of understanding customer context and validating assumptions thoroughly.oLearned to ensure solutions align with user needs, their environment, and behaviors for future projects.
Story 14: WEAKNESS - Weakness in Technical Feasibility EvaluationShort Bullet-Point Version (STAR)Situation:o        My weakness is limited hands-on coding experience, which can make evaluating technical feasibility challenging. At Treinta, I was tasked with assessing the feasibility of redesigning the app’s look and feel to improve accessibility.Task:o        Collaborate with the engineering team to evaluate the redesign’s feasibility and provide a recommendation to the group product manager, balancing technical constraints and business priorities.Action:o        Met with the engineering manager to understand technical requirements and challenges, asking targeted questions about dependencies, timelines, and resource allocation.o        Learned that the redesign would require over three months of effort due to the need for new microfrontends and components.o        Presented findings to the group product manager, explaining the impact on timelines and high-priority metrics.o        Recommended focusing on retention and engagement-driving features instead of the redesign.Result:o        The group product manager accepted my recommendation, avoiding unnecessary development costs.o        The team prioritized impactful features, leading to an 11% improvement in retention and a 9% increase in the DAU-to-MAU ratio.o        Demonstrated how leveraging engineering relationships bridges technical knowledge gaps effectively.
Full Version (STAR)•Situation:oOne of my weaknesses is limited hands-on coding experience, which can occasionally make it challenging to evaluate the technical feasibility of projects independently. During my time at Treinta, our group product manager tasked me with improving the app’s overall look and feel, which had accessibility issues due to its MVP nature. While I acknowledged the importance of this task, I hypothesized that implementing it would require significant development effort and could impact the team’s ability to deliver on more critical metrics.•Task:oMy task was to collaborate with the engineering team to assess the feasibility of the redesign and present a recommendation to the group product manager. The goal was to ensure that any decision aligned with technical constraints and strategic business priorities.•Action:oBegan by meeting with the engineering manager to gain a detailed understanding of the technical requirements and challenges. I carefully listened as he outlined the complexities of the development, including creating new microfrontends and additional components in a separate repository.oAsked targeted questions about dependencies, timelines, and resource allocation to clarify the impact of the redesign on ongoing and future projects.oConfirmed that implementing the change sustainably would take over three months, significantly delaying other high-priority features.oPresented my findings to the group product manager, explaining the technical effort required and the potential trade-offs. I recommended refocusing the team’s efforts on features that would drive retention and engagement, which were the key business metrics at the time.•Result:oThe group product manager agreed with my recommendation, allowing the team to prioritize features that had a direct impact on retention and engagement.oThis decision contributed to an 11% improvement in retention and a 9% increase in the DAU-to-MAU ratio over time.oBy leveraging my strong relationship with the engineering team, I effectively bridged my technical knowledge gap and ensured the team remained focused on strategic goals, avoiding unnecessary development costs.
Story 15: Capital One - Improving IRIS Gen AI Search with Query ExpansionShort Bullet-Point Version (STAR)Situation:o        Gen AI Product Manager Intern at Capital One EPX division.o        Scope: IRIS, an internal AI-powered search product.o        Faced with ambiguous question: What feature could improve user experience? You will present at the end to leadership! (John m and maulin patel)o        Added challenges: manager gone 4/10 weeks + limited knowledge of product intricacies.Task:o        Align with diverse stakeholders and translate user needs into a clear business opportunity.o        Deliver a feasible, impactful product improvement.Action:o        Partnered with data scientists, engineers, and product teams via 1:1 interviews.o        Discovered common pain point: low recall (esp. highlighted by Agent Assist team).o        Researched extensively on search tech; shortlisted 3 improvements (Graph RAG, Query Expansion, Agentic RAG).o        Collaborated with data engineering and research to evaluate impact, effort, and risks.o        Selected Query Expansion; built prototype through live coding to validate hypothesis.o        Created PRD for engineers/data scientists and an executive slide deck for VP & MVP leadership.Result:o        Earned leadership buy-in to include feature in roadmap.o        Feature projected to increase recall by 14% and deliver ~$380K in OpEx savings/year.
Full Version (STAR)•        Situation:o        During my internship at Capital One, I worked as a Gen AI Product Manager Intern in the EPX division, focused on enabling internal AI solutions. My project was IRIS, an internal technical search tool designed to allow AI-powered search based on intent and meaning rather than just keywords.o        When I joined, I was faced with a highly ambiguous challenge: What feature should we develop to improve IRIS’s user experience? This was complicated further by my manager being out for 4 of the 10 weeks of my internship and my limited familiarity with the product.•        Task:o        My responsibility was to reduce this ambiguity by partnering with stakeholders, uncovering real user needs, and translating them into a concrete product improvement that aligned with business priorities.•        Action:o        Stakeholder Engagement: Held exhaustive 1:1 interviews with key stakeholders—data scientists, engineers, and product teams consuming our APIs. Consistently heard a shared pain point: users needed higher recall in searches. One critical insight came from the Agent Assist team: they needed a “Google-like” experience to help agents find answers faster, directly impacting customer satisfaction.o        Research & Hypothesis Formation: Conducted in-depth research on search technology—both Capital One’s implementation and industry best practices. Narrowed down three potential solutions: Graph RAG, Query Expansion, and Agentic RAG.o        Feasibility Analysis: Partnered with data engineering and research teams to assess each option’s user impact, implementation effort, and risks.o        Prototyping & Validation: Chose Query Expansion as the most feasible. Built a prototype through live coding to test the hypothesis, demonstrating improved recall.o        Communication & Buy-In: Developed a PRD to document rationale and technical requirements for engineers and data scientists. Simultaneously created and delivered an executive presentation to VP Maulin Patel and Managing VP John Morgan to secure leadership support.•        Result:o        Secured buy-in to include Query Expansion in the IRIS roadmap.o        Projected to improve recall by 14% and deliver ~$380K in annual OpEx savings.o        Personally recognized for driving clarity from ambiguity, fostering cross-functional collaboration, and effectively influencing senior leadership through clear, data-driven communication.o        Learned to thrive in uncertain environments, balancing innovation with execution while aligning diverse stakeholders around a common vision.

Story 16: Personal Project - NBA Betting Agent (AI & Vibe Coding)
Short Bullet-Point Version (STAR)
Situation:
o        In my free time, combining my interests in AI, sports, and product development, I wanted to build a practical tool to analyze NBA betting opportunities and detect arbitrage using LLMs and APIs.
Task:
o        I tasked myself with building an end-to-end web application that integrates real-time data from various APIs (NBA, Odds, News, Wikipedia).
Action:
o        Architected and developed a full Streamlit application using context-enriched LLM prompting, aggregating real-time data from 4 APIs (NBA stats, Odds, News, Wikipedia) into structured context windows.
o        Implemented complex logic for arbitrage detection across moneyline, spread, and totals markets to guarantee profit stake sizing.
o        Engineered an AI-powered insights engine using an LLM to compute "Model Strength", "Market Agreement", and "Perceived News Risk".
o        Built AI guardrails: input sanitization against prompt injection, exponential backoff retry logic, strict token/timeout limits, and safe JSON parsing with fallback defaults.
o        Later integrated MCP (Model Context Protocol) to expose the betting agent's capabilities as composable tools for external AI orchestration.
Result:
o        Successfully launched a functional NBA Betting Agent that provides edge calculation, confidence breakdowns, and arbitrage detection.
o        Demonstrated deep, hands-on knowledge of context window engineering, prompt design, multi-API data orchestration, MCP integration, and AI safety patterns (Vibe Coding), reinforcing my capabilities as an AI Product Manager.

Full Version (STAR)
•        Situation:
o        Outside of my professional roles, I am passionate about "Vibe Coding" and building AI applications to solve real problems. I saw an opportunity to apply LLMs to sports betting analysis—an area rich with unstructured data (news) and structured data (odds, stats) where market inefficiencies like arbitrage exist.
•        Task:
o        My objective was to develop an end-to-end AI agent capable of aggregating real-time NBA data, identifying profitable arbitrage opportunities, and providing LLM-driven betting recommendations based on a holistic view of the market.
•        Action:
o        I architected and built a complete web application utilizing Streamlit, Python, and external APIs (NBA, The Odds API, News API, Wikipedia).
o        I designed the system to normalize odds data across sportsbooks and implemented algorithms to detect arbitrage opportunities, complete with guaranteed profit stake sizing.
o        I designed a context enrichment pipeline that aggregates real-time data from 4 APIs (NBA stats, The Odds API, News API, Wikipedia) into structured prompts, enabling the LLM to compute nuanced metrics like "Model Strength", "Market Agreement", and "Perceived News Risk" without requiring a vector database or retrieval layer.
o        I implemented AI guardrails: input sanitization to protect against prompt injection and malicious control characters, exponential backoff retry logic for transient API failures, strict token limits and request timeouts for resource management, and safe JSON parsing with fallback defaults to prevent crashes.
o        I later added MCP (Model Context Protocol) integration to expose the agent's analysis capabilities as composable tools, enabling external AI systems to invoke betting analysis, arbitrage detection, and odds comparison programmatically.
o        I built this rapidly using AI development tools, showcasing my ability to translate a complex product vision into a working application efficiently.
•        Result:
o        The final product is a robust, multi-featured NBA Betting Agent that provides edge calculation, confidence breakdowns, and arbitrage detection.
o        Building this project deepened my practical, hands-on understanding of LLM application architecture, prompt engineering, context window optimization, multi-API data orchestration, MCP integration, and AI safety/guardrails engineering--skills that make me a technical and effective Gen AI Product Manager today.

"""

# -------------------------------------------------------------------
# Story Index for Matching
# -------------------------------------------------------------------
STORY_INDEX = """
Story 1: Mastercard — transactional intelligence model, +7% per-user spend
Story 2: Treinta — POS activation challenges, +17pp activation rate
Story 3: Mastercard — DR market share analysis, uncovered competitor activity
Story 4: Treinta — Agile processes, doubled release cadence
Story 5: Treinta — mentoring underperforming intern to PM successor
Story 6: Treinta — data-driven redirect, +9pp DAU/MAU
Story 7: Mastercard — RStudio bootcamp for 20+ analysts across LatAm
Story 8: Cmillas — nonprofit, 90+ children's education support
Story 9: Visa — agro GTM plan, $11M revenue potential
Story 10: Treinta — call center reactivation, +9-11% retention
Story 11: Treinta — retention through product development, +11pp retention, +9pp DAU/MAU
Story 12: Treinta — inventory UX redesign, usage from 28% to 47%
Story 13: Treinta — Book Lite failure, pivot to 3K+ paying users
Story 14: WEAKNESS — technical feasibility evaluation
Story 15: Capital One — IRIS GenAI search, query expansion, +14% recall, ~$380K savings
Story 16: Personal Project — NBA Betting Agent, AI/LLM, Arbitrage, context-enriched prompting, multi-API orchestration, MCP, AI guardrails
"""

# -------------------------------------------------------------------
# Golden Examples
# -------------------------------------------------------------------
GOLDEN_EXAMPLES = """

These are examples of the target voice, tone, and structure. Match their style.

--- EXAMPLE 1: CAPITOL AI ---
Dear Capitol Team,

I'm applying for the Product Manager role at Capitol. On a personal level, this space truly resonates with me. I enjoy going deep on how AI systems actually work, not just conceptually, but technically. During my AI coursework and specializations, I was especially motivated by understanding how deep learning models are trained, evaluated, and fail. That curiosity carried directly into my recent internship as a GenAI Product Manager at Capital One, where I worked on improving an AI-powered enterprise search and RAG systems. I found myself genuinely enjoying the technical details: learning how retrieval pipelines function, how vector databases and rerankers affect relevance, and how evaluation metrics translate into real user outcomes. That experience confirmed that I want to work on AI products where correctness, trust, and operational usability matter.

My background makes me a strong fit for this role. I bring 6 years of experience across product management, consulting, and AI-focused product work. I started my career in strategy and analytics roles at Mastercard Advisors, where I worked on complex fintech problems, conducted deep data analysis, and translated insights into executive-level recommendations. That foundation trained me to synthesize user needs, data insights, and technical constraints into clear decisions, and to communicate them effectively to senior stakeholders.

I later joined Treinta, a Y Combinator-backed fintech startup, as the company's first Product Manager and one of its earliest employees. There, I operated fully end-to-end: defining product strategy, leading Agile squads, writing PRDs, user stories and success criteria, prioritizing backlogs, and working hands-on with engineering and design. I also took ownership beyond traditional product work, including leading a reactivation call-center initiative from scratch when product changes alone were not enough to move retention. That ownership mindset helped Treinta scale across 18+ Latin American countries, reach over one million users, and ultimately raise a $60M Series A, the largest in Colombia's history.

Across these roles, I have become comfortable working with unstructured data, ambiguous enterprise workflows, and high stakes use cases. I have partnered closely with both technical and non-technical stakeholders, written detailed technical documentation, and led teams with minimal oversight. I take pride in execution quality, bring a strong bias toward action, and see it as my responsibility to create clarity rather than wait for direction.

At Capitol AI, I see an opportunity to have real impact, helping shape agentic workflows and AI products that organizations can trust and act on. I would love to bring my experience in AI product development, analytics-driven decision making, and startup execution to help Capitol build and scale decision-grade AI systems for its customers.

Thank you for your time and consideration. I would love the opportunity to continue the conversation.

Best,
Nicolas De Castro


--- EXAMPLE 2: SCOPELY ---
Dear Scopely Hiring Team,

I'm applying to Scopely's MBA Product Leadership Rotational Program because it's the rare combination I'm looking for: live products at massive scale, high accountability, and a culture that rewards disciplined experimentation. I'm a massive gamer, and I'm drawn to building great player experiences with a top-tier team.

I bring 6+ years across product, strategy, and analytics, with a track record of owning ambiguous problems end-to-end and turning them into measurable outcomes. At Treinta (YC fintech) I joined as the first Product Manager and 10th employee, owning the flagship product across discovery, roadmap, requirements (PRDs, user stories, success criteria), delivery, and iteration. Because we were scaling fast across 18+ countries and 1M+ users, I learned to think in systems: how changes affect retention loops, onboarding, pricing, support load, and long-term product health. That operating cadence, ship, measure, learn, double down, helped improve core business metrics as the company scaled through its $60M Series A.

What makes me particularly relevant for Scopely is the mix of analytics depth and product execution. In Mastercard (Advisors) and at Treinta, I worked hands-on with large datasets, using Python and RStudio to build segmentation models and engagement analyses across millions of users/transactions, then translated those findings into decisions, prioritization, and clear narratives for senior stakeholders. I'm comfortable moving from player/user behavior patterns (hypothesis, experiment design, success metrics, iteration), which maps directly to live ops work: identifying growth opportunities, validating them quickly, and improving product health over time.

I also thrive in cross-functional environments where alignment is the job. I've worked closely with engineering, design, data, ops, and GTM partners to prioritize tradeoffs and keep execution moving, and I'm comfortable presenting product updates and recommendations to senior leaders. That's the same muscle your rotational program demands: influence without authority, clear executive storytelling, and the ability to drive outcomes across multiple teams and disciplines.

I'm drawn to Scopely because of the way you operate: dream big, start small, and let evidence guide where you double down. That mindset keeps teams grounded in real player needs while still leaving room for bold creativity, which is exactly how I like to build. I would love to bring my product ownership, analytics rigor, and live-iteration mindset to help Scopely's teams ship features that improve player experience and drive durable growth across your portfolio.

Thank you for your time and consideration. I would love to discuss how my background in end-to-end product leadership, experimentation, and data-driven decision-making can contribute to Scopely's next chapter.

Best,
Nicolas De Castro


--- EXAMPLE 3: ELISEAI ---
Dear EliseAI Hiring Team,

I'm applying for the Founding Senior Product Manager role on the healthcare team because it matches exactly how I've built products at my best: owning problems end-to-end, operating in ambiguity, and shipping zero-to-one products that materially improve how real people experience critical services.

I've spent over six years in product, consulting, and analytics-heavy roles, most notably as the first Product Manager and 10th employee at Treinta (YC). There, I owned the flagship product end-to-end, from strategy devising, user discovery and stakeholder management (including founders) to PRDs and user stories, to sprint execution, launches, and in-field product validation. One concrete example is Treinta Lite, a zero-to-one MVP I identified, scoped, and drove to execution across engineering, design, and growth in 2.5 months. We validated unmet user needs quickly, iterated fast with limited data, and scaled what worked. That ownership model helped Treinta grow to 1M+ users across 18 countries and raise a $60M Series A, the largest in Colombia's history.

A core strength I bring is deep, hypothesis-driven user discovery. I don't just talk to users, I structure discovery to uncover real workflow pain points using supervised and unsupervised methods, combining qualitative insight with data. Whether working with SMBs at Treinta, bank partners at Visa, or enterprise teams at Capital One, I've consistently translated messy, real-world workflows into clear product strategies and intuitive experiences.

Execution-wise, I'm highly detail-oriented, disciplined, highly communicative and collaborative. I've written dozens of PRDs, user stories, acceptance criteria, and run agile ceremonies as a heavy Jira user. My consulting background trained me to communicate crisply at the executive level using PowerPoint, while my PM experience ensures engineers get the clarity they need to move fast without rework. I'm comfortable making decisions with incomplete information, defining success metrics tied to operational efficiency and user experience, and iterating rapidly as new data emerges.

I'm fully comfortable working in person five days a week and see this role as a natural continuation of work I've already done. At Treinta, I grew into a Group Product Manager role, leading product squads. I helped define product standards by implementing clear metrics, improving discovery and delivery processes, mentoring junior PMs, and raising the bar on product processes and execution.

I'm especially drawn to EliseAI because the work is real, high-stakes, and impact-driven. Improving patient access, reducing administrative burden, and embedding AI directly into healthcare workflows is exactly the kind of problem where strong product leadership matters. I also strongly resonate with the no-fluff, high-ownership culture you describe. At Treinta, I thrived in an environment with full autonomy, no micromanagement, and high expectations, and I'm intentionally seeking that again.

Best,
Nicolas De Castro


--- EXAMPLE 4: CLASSDOJO ---
Dear ClassDojo Team,

I'm drawn to ClassDojo because it combines two things that matter deeply to me: building products end-to-end at meaningful scale, and expanding access to education in ways that genuinely improve children's lives. The size and scope of ClassDojo, small, focused teams with massive global impact, is exactly the environment where I do my best work. I'm drawn to roles where I can own the full arc of product development, from discovery and strategy to execution, growth, and monetization, rather than being isolated in a narrow slice of the stack.

Education has also been a personal driver throughout my life. Before business school, I co-founded a nonprofit called Cmillas, which built a volunteer network to support children from marginalized communities. Through tutoring and mentorship, we helped more than 90 students pass their school classes and stay engaged in learning. That experience shaped how I think about education, not just as content, but as motivation, belonging, and joy. ClassDojo's mission to give every child an education they love resonates strongly with that perspective.

Professionally, I've spent my career building and scaling products in environments that require strong judgment, speed, and ownership. At Treinta, a Y Combinator-backed fintech, I joined as the 10th employee and first Product Manager, working directly with the founders. I helped take products from zero to product-market fit, led discovery and experimentation, built monetized SaaS offerings for small businesses, and partnered across product, growth, and operations. Operating in a resource-constrained environment, I drove initiatives spanning retention, onboarding, and revenue, contributing to Treinta's growth across 18 countries and its $60M Series A, the largest in Colombia's history.

I bring a strong grasp of product strategy and intuition, shaped by both consulting and hands-on execution. I'm deeply comfortable with hypothesis-driven discovery, user research, and data-informed decision-making, using tools ranging from Excel and SQL to Python and R when needed. I've built forecasts, managed P&Ls, and balanced business viability with user value. I also thrive in ambiguity: moving faster than is comfortable, learning quickly, and following through until ideas become real products in users' hands.

I'm particularly drawn to this role's focus: discovering new revenue models, validating them with users, and scaling what works. I've done this before, and I would love to do it again in service of a mission as meaningful as ClassDojo's. I would be glad to partner closely with your founders and product leaders to build new business lines that children and families truly love.

Thank you for your time and consideration, I would love the opportunity to continue the conversation.

Best,
Nicolas De Castro


"""

# -------------------------------------------------------------------
# Positioning Guide
# -------------------------------------------------------------------
POSITIONING_GUIDE = {
    "AI PM": "Lead with Story 15 (Capital One) + technical fluency. Second dimension: Treinta ownership.",
    "Consumer PM": "Lead with Treinta stories (11, 12, 2). Emphasize activation, retention, 1M+ users, user research.",
    "Gaming PM": "Lead with Treinta engagement/retention + personal gaming interest. Emphasize metrics fluency.",
    "Startup PM": "Lead with Treinta (employee #10, zero-to-one, ambiguity). Emphasize scrappy execution.",
    "Strategy & Ops": "Lead with Mastercard consulting + Visa GTM. Emphasize structured problem solving.",
    "Mission-driven": "Include Cmillas (Story 8) naturally. Lead with Treinta or most relevant experience.",
    "Other": "Balance across experiences based on JD requirements."
}
